#-------------------------------------------------------------------------------
# Output VPC
#-------------------------------------------------------------------------------

output "vpc_id" {
  description = "The unique identifier of the VPC network."
  value       = try(google_compute_network.vpc[0].id, null)
}

output "vpc_name" {
  description = "The name of the VPC network."
  value       = try(google_compute_network.vpc[0].name, null)
}

output "vpc_self_link" {
  description = "The URI (self_link) of the VPC network. Pass this to subnet/firewall modules."
  value       = try(google_compute_network.vpc[0].self_link, null)
}

output "vpc_gateway_ipv4" {
  description = "The default IPv4 gateway address of the network."
  value       = try(google_compute_network.vpc[0].gateway_ipv4, null)
}

output "vpc_routing_mode" {
  description = "The routing mode of the VPC (REGIONAL or GLOBAL)."
  value       = try(google_compute_network.vpc[0].routing_mode, null)
}

output "vpc_mtu" {
  description = "The MTU configured on the VPC."
  value       = try(google_compute_network.vpc[0].mtu, null)
}

#-------------------------------------------------------------------------------
# Output_shared_vpc_#
#-------------------------------------------------------------------------------


output "host_project_id" {
  value       = google_compute_shared_vpc_host_project.host[*].project
  description = "The ID of the Google Cloud project acting as the host project for the Shared VPC."
}

output "service_project_id" {
  value       = google_compute_shared_vpc_service_project.service1[*].service_project
  description = "The ID of the Google Cloud project acting as the service project for the Shared VPC."
}

output "labels_id" {
  description = "The full label ID generated by the labels module. Used as the base name for all resources."
  value       = module.labels.id
}


output "static_route_ids" {
  description = "List of static route IDs."
  value       = google_compute_route.static_route[*].id
}

output "static_route_names" {
  description = "List of static route names."
  value       = google_compute_route.static_route[*].name
}

output "static_route_self_links" {
  description = "List of static route self_links."
  value       = google_compute_route.static_route[*].self_link
}

output "service_networking_connection_id" {
  description = "The ID of the private service networking connection."
  value       = try(google_service_networking_connection.default[0].id, null)
}

output "service_networking_peering_ranges" {
  description = "Reserved peering ranges used by the service networking connection."
  value       = try(google_service_networking_connection.default[0].reserved_peering_ranges, null)
}

output "private_ip_alloc_ids" {
  description = "List of private IP allocation resource IDs."
  value       = google_compute_global_address.private_ip_alloc[*].id
}

output "private_ip_alloc_names" {
  description = "List of private IP allocation names."
  value       = google_compute_global_address.private_ip_alloc[*].name
}

output "private_ip_alloc_addresses" {
  description = "List of reserved private IP addresses."
  value       = google_compute_global_address.private_ip_alloc[*].address
}

output "private_ip_alloc_self_links" {
  description = "List of private IP allocation self_links."
  value       = google_compute_global_address.private_ip_alloc[*].self_link
}

output "nat_router_id" {
  description = "The ID of the Cloud Router."
  value       = try(google_compute_router.nat_router[0].id, null)
}

output "nat_router_name" {
  description = "The name of the Cloud Router."
  value       = try(google_compute_router.nat_router[0].name, null)
}

output "nat_router_self_link" {
  description = "The self_link of the Cloud Router. Can be referenced by other router resources."
  value       = try(google_compute_router.nat_router[0].self_link, null)
}

output "nat_id" {
  description = "The ID of the Cloud NAT gateway."
  value       = try(google_compute_router_nat.nat[0].id, null)
}

output "nat_name" {
  description = "The name of the Cloud NAT gateway."
  value       = try(google_compute_router_nat.nat[0].name, null)
}

output "nat_router" {
  description = "The Cloud Router name this NAT gateway is attached to."
  value       = try(google_compute_router_nat.nat[0].router, null)
}

output "nat_region" {
  description = "The region the Cloud NAT gateway is deployed in."
  value       = try(google_compute_router_nat.nat[0].region, null)
}