# name: changelog
# permissions: write-all
# on:
#   push:
#     tags:
#       - "*"
#   workflow_dispatch:
# jobs:
#   changelog:
#     uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@master
#     with:
#       branch: 'master' 
#     secrets:
#       GITHUB: ${{ secrets.GITHUB_TOKEN }

name: changelog
permissions: write-all
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  call-workflow-changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@master
    secrets: inherit
    with:
      branch: 'master'