name: tfsec
permissions: write-all
on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
  workflow_dispatch:
jobs:
  tfsec:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/security-tfsec.yml@v2
    with:
      working_directory: '.'
    secrets:
          GITHUB: ${{ secrets.GCP_GITHUB_TOKEN }}