name: tf-checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'
jobs:
  complete:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'
      provider: gcp
      enable_plan: true
      show_plan: false
      project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets: 
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}